#!/usr/bin/env python3

import re
from datetime import datetime, timedelta
import sys

# check that arguments are fine
if len(sys.argv) == 1:
    print("Usage: ./autocommit <assignment due date>", file=sys.stderr)
    exit(1)

due_date = sys.argv.pop(1)


if due_date.lower() in ["today", "--today"]:
    due_date = f"{datetime.now():%d.%m.%Y}"
elif not re.match(r"\d{2}\.\d{2}\.\d{4}", due_date):
    from random import randint

    random_day = datetime.now() + timedelta(randint(-1000, 1000))
    print("Due date must be in format:", f"{random_day:%d.%m.%Y}")
    exit(1)

import os

os.system(f"git add . && git commit -am 'add assignments due {due_date}'")
