#!/usr/bin/bash


dest="$1/main";
source="$1/main.cpp";


if [ -z "$1" ]
  then
    echo "No argument supplied!";
    exit 1;
elif [ ! -f "$source" ]
    then
        echo "File '$source' not found!";
        exit 1;
fi


echo "Generating file...";
make "$source" "$dest" && {
  printf "\nRunning file: $dest\n\n";
  ./$dest;
}
