run: FahrenheitToCentigradeTemp.java
	javac -encoding UTF-8 FahrenheitToCentigradeTemp.java
	java FahrenheitToCentigradeTemp

test:
	javac -encoding UTF-8 FahrenheitToCentigradeTemp.java
	java FahrenheitToCentigradeTemp 1 3.14 -40
